### ISSUE TITLE
Préparation de l'environnement

### ISSUE THREAD

**Issue by Abbassihraf** [Abbassihraf/Covitest#1]
Préparer le terrain pour un flux de travail Organizer, un code réutilisable et des tâches automatisées

 

- [x] git clone /lien Repository/ ou Fork

 

- [x] npm install /packages/

 

- [x] Watching concatenation Préfixage avec NPM Scripts

 

- [x] Compression du CSS et Javascript avec NPM Scripts

**Comment by Abbassihraf** [comment]
@youssefbm 
Bonjour Monsieur, si possible vérifier le package.json.

**Comment by youssefbm** [comment]
Hello Achraf, avez vous pensé aux sections qui se répète entre les deux pages?

**Comment by Abbassihraf** [comment]
Oui, j'ai trouvé la solution
